#ifndef SVAHADEFINE_H
#define SVAHADEFINE_H

#define MAX_MAC_INLIST      100
#define MAX_MAC_GROUPS      10

#define DT_MODE_EVERY_DAY   1
#define DT_MODE_EVERY_WEEK  2
#define DT_MODE_EVERY_MONTH 3


#endif // SVAHADEFINE_H
